import "./globals.css";
import { Pixelify_Sans } from "next/font/google";

const pixelify = Pixelify_Sans({
  subsets: ["latin"],
  variable: "--font-pixelify",
});

export const metadata = {
  title: "Next.js",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body
        className={`${pixelify.variable} bg-center bg-cover bg-[url(https://static.vecteezy.com/system/resources/thumbnails/028/241/284/original/abstract-animated-outline-topographic-contour-map-moving-waves-on-black-background-4k-looped-animation-video.jpg)] flex justify-center items-center h-screen w-screen`}
      >
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
